##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  guns配置  ###################
guns:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  session-open: false #是否开启session验证 (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  session-invalidate-time: 1800 #session失效时间 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session 单位：秒

###################  项目启动端口  ###################
server:
  port: 8888

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag

###################  统计端  ###################
wecaturl: 127.0.0.1
wecatport: 9050

###################  调度器地址  ###################
data:
  url: http://127.0.0.1:9060/

###################  spring配置  ###################
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.common.persistence.model
  global-config:
    id-type: 1  #1:数据库ID自增   2:用户输入id   3:全局唯一id(IdWorker)   4:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
#      url: jdbc:mysql://10.12.11.185:3306/giveu_job_center?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#      username: giveu_jc_rw
#      password: Rw_giveujc$201807

#      url: jdbc:mysql://10.11.11.225:3306/giveu_job_guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#      username: giveu_jc_rw
#      password: RW_giveU_JC$092018

      url: jdbc:mysql://localhost:3306/giveu_job_center?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      filters: log4j,wall,mergeStat

logging:
  level: debug
  file: /data/log/springboot/guns/guns.log


---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: test
  datasource:
      url: jdbc:mysql://10.12.11.185:3306/giveu_job_center?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: giveu_jc_rw
      password: Rw_giveujc$201807

      filters: log4j,wall,mergeStat

logging:
  level: debug
  file: /data/log/springboot/guns/guns.log

---

##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: prod
#  devtools:
#    restart:
#      enabled: true
  datasource:
      url: jdbc:mysql://10.11.11.225:3306/giveu_job_center?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: giveu_jc_rw
      password: RW_giveU_JC$092018
      filters: log4j,wall,mergeStat

logging:
  level: warn
  file: /data/log/springboot/guns/guns.log


---

##########################################################
###################  备份环境环境的profile  ###################
##########################################################
spring:
  profiles: bak
#  devtools:
#    restart:
#      enabled: true
  datasource:
      url: jdbc:mysql://10.12.13.98:3306/giveu_job_center?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      filters: log4j,wall,mergeStat


logging:
  level: warn
  file: /data/log/springboot/guns/guns.log







